/* This file is released under LGPL2.
   See COPYING.LGPL2 in root directory for more details
*/

/*
   Created for Unicorn Engine by Amaan Qureshi <amaanq12@gmail.com>, 2025
   Copyright 2025 Amaan Qureshi
*/

#ifndef UNICORN_LOONGARCH_H
#define UNICORN_LOONGARCH_H

#ifdef __cplusplus
extern "C" {
#endif

#ifdef _MSC_VER
#pragma warning(disable : 4201)
#endif

//> LoongArch CPU
typedef enum uc_cpu_loongarch {
    UC_CPU_LOONGARCH_LA464,

    UC_CPU_LOONGARCH_ENDING
} uc_cpu_loongarch;

//> LoongArch registers
typedef enum uc_loongarch_reg {
    UC_LOONGARCH_REG_INVALID = 0,

    // General purpose registers (GPR)
    UC_LOONGARCH_REG_R0,
    UC_LOONGARCH_REG_R1,
    UC_LOONGARCH_REG_R2,
    UC_LOONGARCH_REG_R3,
    UC_LOONGARCH_REG_R4,
    UC_LOONGARCH_REG_R5,
    UC_LOONGARCH_REG_R6,
    UC_LOONGARCH_REG_R7,
    UC_LOONGARCH_REG_R8,
    UC_LOONGARCH_REG_R9,
    UC_LOONGARCH_REG_R10,
    UC_LOONGARCH_REG_R11,
    UC_LOONGARCH_REG_R12,
    UC_LOONGARCH_REG_R13,
    UC_LOONGARCH_REG_R14,
    UC_LOONGARCH_REG_R15,
    UC_LOONGARCH_REG_R16,
    UC_LOONGARCH_REG_R17,
    UC_LOONGARCH_REG_R18,
    UC_LOONGARCH_REG_R19,
    UC_LOONGARCH_REG_R20,
    UC_LOONGARCH_REG_R21,
    UC_LOONGARCH_REG_R22,
    UC_LOONGARCH_REG_R23,
    UC_LOONGARCH_REG_R24,
    UC_LOONGARCH_REG_R25,
    UC_LOONGARCH_REG_R26,
    UC_LOONGARCH_REG_R27,
    UC_LOONGARCH_REG_R28,
    UC_LOONGARCH_REG_R29,
    UC_LOONGARCH_REG_R30,
    UC_LOONGARCH_REG_R31,

    // Floating point registers (FPR)
    UC_LOONGARCH_REG_F0,
    UC_LOONGARCH_REG_F1,
    UC_LOONGARCH_REG_F2,
    UC_LOONGARCH_REG_F3,
    UC_LOONGARCH_REG_F4,
    UC_LOONGARCH_REG_F5,
    UC_LOONGARCH_REG_F6,
    UC_LOONGARCH_REG_F7,
    UC_LOONGARCH_REG_F8,
    UC_LOONGARCH_REG_F9,
    UC_LOONGARCH_REG_F10,
    UC_LOONGARCH_REG_F11,
    UC_LOONGARCH_REG_F12,
    UC_LOONGARCH_REG_F13,
    UC_LOONGARCH_REG_F14,
    UC_LOONGARCH_REG_F15,
    UC_LOONGARCH_REG_F16,
    UC_LOONGARCH_REG_F17,
    UC_LOONGARCH_REG_F18,
    UC_LOONGARCH_REG_F19,
    UC_LOONGARCH_REG_F20,
    UC_LOONGARCH_REG_F21,
    UC_LOONGARCH_REG_F22,
    UC_LOONGARCH_REG_F23,
    UC_LOONGARCH_REG_F24,
    UC_LOONGARCH_REG_F25,
    UC_LOONGARCH_REG_F26,
    UC_LOONGARCH_REG_F27,
    UC_LOONGARCH_REG_F28,
    UC_LOONGARCH_REG_F29,
    UC_LOONGARCH_REG_F30,
    UC_LOONGARCH_REG_F31,

    UC_LOONGARCH_REG_PC,

    UC_LOONGARCH_REG_ENDING,

    //> Alias registers
    UC_LOONGARCH_REG_ZERO = UC_LOONGARCH_REG_R0,
    UC_LOONGARCH_REG_RA = UC_LOONGARCH_REG_R1,
    UC_LOONGARCH_REG_TP = UC_LOONGARCH_REG_R2,
    UC_LOONGARCH_REG_SP = UC_LOONGARCH_REG_R3,
    UC_LOONGARCH_REG_A0 = UC_LOONGARCH_REG_R4,
    UC_LOONGARCH_REG_A1 = UC_LOONGARCH_REG_R5,
    UC_LOONGARCH_REG_A2 = UC_LOONGARCH_REG_R6,
    UC_LOONGARCH_REG_A3 = UC_LOONGARCH_REG_R7,
    UC_LOONGARCH_REG_A4 = UC_LOONGARCH_REG_R8,
    UC_LOONGARCH_REG_A5 = UC_LOONGARCH_REG_R9,
    UC_LOONGARCH_REG_A6 = UC_LOONGARCH_REG_R10,
    UC_LOONGARCH_REG_A7 = UC_LOONGARCH_REG_R11,
    UC_LOONGARCH_REG_T0 = UC_LOONGARCH_REG_R12,
    UC_LOONGARCH_REG_T1 = UC_LOONGARCH_REG_R13,
    UC_LOONGARCH_REG_T2 = UC_LOONGARCH_REG_R14,
    UC_LOONGARCH_REG_T3 = UC_LOONGARCH_REG_R15,
    UC_LOONGARCH_REG_T4 = UC_LOONGARCH_REG_R16,
    UC_LOONGARCH_REG_T5 = UC_LOONGARCH_REG_R17,
    UC_LOONGARCH_REG_T6 = UC_LOONGARCH_REG_R18,
    UC_LOONGARCH_REG_T7 = UC_LOONGARCH_REG_R19,
    UC_LOONGARCH_REG_T8 = UC_LOONGARCH_REG_R20,
    UC_LOONGARCH_REG_U0 = UC_LOONGARCH_REG_R21,
    UC_LOONGARCH_REG_FP = UC_LOONGARCH_REG_R22,
    UC_LOONGARCH_REG_S0 = UC_LOONGARCH_REG_R23,
    UC_LOONGARCH_REG_S1 = UC_LOONGARCH_REG_R24,
    UC_LOONGARCH_REG_S2 = UC_LOONGARCH_REG_R25,
    UC_LOONGARCH_REG_S3 = UC_LOONGARCH_REG_R26,
    UC_LOONGARCH_REG_S4 = UC_LOONGARCH_REG_R27,
    UC_LOONGARCH_REG_S5 = UC_LOONGARCH_REG_R28,
    UC_LOONGARCH_REG_S6 = UC_LOONGARCH_REG_R29,
    UC_LOONGARCH_REG_S7 = UC_LOONGARCH_REG_R30,
    UC_LOONGARCH_REG_S8 = UC_LOONGARCH_REG_R31,

    // FPR aliases
    UC_LOONGARCH_REG_FA0 = UC_LOONGARCH_REG_F0,
    UC_LOONGARCH_REG_FA1 = UC_LOONGARCH_REG_F1,
    UC_LOONGARCH_REG_FA2 = UC_LOONGARCH_REG_F2,
    UC_LOONGARCH_REG_FA3 = UC_LOONGARCH_REG_F3,
    UC_LOONGARCH_REG_FA4 = UC_LOONGARCH_REG_F4,
    UC_LOONGARCH_REG_FA5 = UC_LOONGARCH_REG_F5,
    UC_LOONGARCH_REG_FA6 = UC_LOONGARCH_REG_F6,
    UC_LOONGARCH_REG_FA7 = UC_LOONGARCH_REG_F7,
    UC_LOONGARCH_REG_FT0 = UC_LOONGARCH_REG_F8,
    UC_LOONGARCH_REG_FT1 = UC_LOONGARCH_REG_F9,
    UC_LOONGARCH_REG_FT2 = UC_LOONGARCH_REG_F10,
    UC_LOONGARCH_REG_FT3 = UC_LOONGARCH_REG_F11,
    UC_LOONGARCH_REG_FT4 = UC_LOONGARCH_REG_F12,
    UC_LOONGARCH_REG_FT5 = UC_LOONGARCH_REG_F13,
    UC_LOONGARCH_REG_FT6 = UC_LOONGARCH_REG_F14,
    UC_LOONGARCH_REG_FT7 = UC_LOONGARCH_REG_F15,
    UC_LOONGARCH_REG_FT8 = UC_LOONGARCH_REG_F16,
    UC_LOONGARCH_REG_FT9 = UC_LOONGARCH_REG_F17,
    UC_LOONGARCH_REG_FT10 = UC_LOONGARCH_REG_F18,
    UC_LOONGARCH_REG_FT11 = UC_LOONGARCH_REG_F19,
    UC_LOONGARCH_REG_FT12 = UC_LOONGARCH_REG_F20,
    UC_LOONGARCH_REG_FT13 = UC_LOONGARCH_REG_F21,
    UC_LOONGARCH_REG_FT14 = UC_LOONGARCH_REG_F22,
    UC_LOONGARCH_REG_FT15 = UC_LOONGARCH_REG_F23,
    UC_LOONGARCH_REG_FS0 = UC_LOONGARCH_REG_F24,
    UC_LOONGARCH_REG_FS1 = UC_LOONGARCH_REG_F25,
    UC_LOONGARCH_REG_FS2 = UC_LOONGARCH_REG_F26,
    UC_LOONGARCH_REG_FS3 = UC_LOONGARCH_REG_F27,
    UC_LOONGARCH_REG_FS4 = UC_LOONGARCH_REG_F28,
    UC_LOONGARCH_REG_FS5 = UC_LOONGARCH_REG_F29,
    UC_LOONGARCH_REG_FS6 = UC_LOONGARCH_REG_F30,
    UC_LOONGARCH_REG_FS7 = UC_LOONGARCH_REG_F31,
} uc_loongarch_reg;

#ifdef __cplusplus
}
#endif

#endif
