/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */
#define TARGET_BIG_ENDIAN 0
#define TARGET_LOONGARCH 1
#define TARGET_LOONGARCH64 1
#define TARGET_NAME "loongarch64"
#define TARGET_NEED_FDT 1
#define TARGET_SUPPORTS_MTTCG 1
#define CONFIG_SOFTMMU 1
